/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PageResponseUserDto } from '../../models/page-response-user-dto';

export interface FilterUser$Params {
  email?: string;
  subLevel?: string;
  page?: number;
  size?: number;
}

export function filterUser(http: HttpClient, rootUrl: string, params?: FilterUser$Params, context?: HttpContext): Observable<StrictHttpResponse<PageResponseUserDto>> {
  const rb = new RequestBuilder(rootUrl, filterUser.PATH, 'get');
  if (params) {
    rb.query('email', params.email, {});
    rb.query('subLevel', params.subLevel, {});
    rb.query('page', params.page, {});
    rb.query('size', params.size, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PageResponseUserDto>;
    })
  );
}

filterUser.PATH = '/users/filter';
