/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { UserAggregateData } from '../../models/user-aggregate-data';

export interface GetUserAggregateData$Params {
}

export function getUserAggregateData(http: HttpClient, rootUrl: string, params?: GetUserAggregateData$Params, context?: HttpContext): Observable<StrictHttpResponse<UserAggregateData>> {
  const rb = new RequestBuilder(rootUrl, getUserAggregateData.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<UserAggregateData>;
    })
  );
}

getUserAggregateData.PATH = '/users/aggregate';
