/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { TextDto } from '../../models/text-dto';

export interface UploadMedia$Params {
      body?: {
'file': Blob;
}
}

export function uploadMedia(http: HttpClient, rootUrl: string, params?: UploadMedia$Params, context?: HttpContext): Observable<StrictHttpResponse<TextDto>> {
  const rb = new RequestBuilder(rootUrl, uploadMedia.PATH, 'post');
  if (params) {
    rb.body(params.body, 'multipart/form-data');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<TextDto>;
    })
  );
}

uploadMedia.PATH = '/questions/upload-media';
