/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { UserExamDto } from '../../models/user-exam-dto';

export interface GetUserAnswers$Params {
  'exam-id': string;
}

export function getUserAnswers(http: HttpClient, rootUrl: string, params: GetUserAnswers$Params, context?: HttpContext): Observable<StrictHttpResponse<UserExamDto>> {
  const rb = new RequestBuilder(rootUrl, getUserAnswers.PATH, 'get');
  if (params) {
    rb.path('exam-id', params['exam-id'], {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<UserExamDto>;
    })
  );
}

getUserAnswers.PATH = '/user-exam/{exam-id}';
