/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SubPlanDto } from '../../models/sub-plan-dto';

export interface GetSubPlanById$Params {
  'plan-id': string;
}

export function getSubPlanById(http: HttpClient, rootUrl: string, params: GetSubPlanById$Params, context?: HttpContext): Observable<StrictHttpResponse<SubPlanDto>> {
  const rb = new RequestBuilder(rootUrl, getSubPlanById.PATH, 'get');
  if (params) {
    rb.path('plan-id', params['plan-id'], {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<SubPlanDto>;
    })
  );
}

getSubPlanById.PATH = '/sub-plans/{plan-id}';
