/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SubPlanDto } from '../../models/sub-plan-dto';

export interface GetEnabledSubPlans$Params {
}

export function getEnabledSubPlans(http: HttpClient, rootUrl: string, params?: GetEnabledSubPlans$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<SubPlanDto>>> {
  const rb = new RequestBuilder(rootUrl, getEnabledSubPlans.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<SubPlanDto>>;
    })
  );
}

getEnabledSubPlans.PATH = '/sub-plans/enabled';
