/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { Choice } from './models/choice';
export type { CreateExamDto } from './models/create-exam-dto';
export type { CreateQuestionDto } from './models/create-question-dto';
export type { CreateResourceDto } from './models/create-resource-dto';
export type { ExamDto } from './models/exam-dto';
export type { ListOfResourcesDto } from './models/list-of-resources-dto';
export type { PageResponseResourceDto } from './models/page-response-resource-dto';
export type { PageResponseUserDto } from './models/page-response-user-dto';
export type { QuestionDto } from './models/question-dto';
export type { RegistrationDto } from './models/registration-dto';
export type { ResourceCollectionDto } from './models/resource-collection-dto';
export type { ResourceDto } from './models/resource-dto';
export type { SubscriptionResponse } from './models/subscription-response';
export type { UserDto } from './models/user-dto';
