/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { Choice } from './models/choice';
export type { ChoiceDto } from './models/choice-dto';
export type { CorrectAnswer } from './models/correct-answer';
export type { CreateChoiceDto } from './models/create-choice-dto';
export type { CreateExamDto } from './models/create-exam-dto';
export type { CreateQuestionDto } from './models/create-question-dto';
export type { CreateResourceDto } from './models/create-resource-dto';
export type { ExamDetailDto } from './models/exam-detail-dto';
export type { ExamDto } from './models/exam-dto';
export type { ExamNameDto } from './models/exam-name-dto';
export type { NumberDto } from './models/number-dto';
export type { PageResponseExamDto } from './models/page-response-exam-dto';
export type { PageResponseResourceDto } from './models/page-response-resource-dto';
export type { PageResponseUserDto } from './models/page-response-user-dto';
export type { QuestionDetailDto } from './models/question-detail-dto';
export type { QuestionDto } from './models/question-dto';
export type { ResourceCollectionDto } from './models/resource-collection-dto';
export type { ResourceDetailDto } from './models/resource-detail-dto';
export type { ResourceDto } from './models/resource-dto';
export type { ResourceInfoDto } from './models/resource-info-dto';
export type { SubPlanDto } from './models/sub-plan-dto';
export type { SubscriptionDto } from './models/subscription-dto';
export type { TextDto } from './models/text-dto';
export type { UpdateSubPlanDto } from './models/update-sub-plan-dto';
export type { UpdateUserExamDto } from './models/update-user-exam-dto';
export type { UserAggregateData } from './models/user-aggregate-data';
export type { UserAnswer } from './models/user-answer';
export type { UserDto } from './models/user-dto';
export type { UserExamDto } from './models/user-exam-dto';
