/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export { UsersService } from './services/users.service';
export { ResourcesService } from './services/resources.service';
export { RegisterService } from './services/register.service';
export { QuestionsService } from './services/questions.service';
export { ExamsService } from './services/exams.service';
export { SubscriptionService } from './services/subscription.service';
export { FilesService } from './services/files.service';
