/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PageResponseExamDto } from '../../models/page-response-exam-dto';

export interface FilterExams$Params {
  title?: string;
  type?: string;
  year?: number;
  requiredSubLevel?: string;
  page?: number;
  size?: number;
}

export function filterExams(http: HttpClient, rootUrl: string, params?: FilterExams$Params, context?: HttpContext): Observable<StrictHttpResponse<PageResponseExamDto>> {
  const rb = new RequestBuilder(rootUrl, filterExams.PATH, 'get');
  if (params) {
    rb.query('title', params.title, {});
    rb.query('type', params.type, {});
    rb.query('year', params.year, {});
    rb.query('requiredSubLevel', params.requiredSubLevel, {});
    rb.query('page', params.page, {});
    rb.query('size', params.size, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PageResponseExamDto>;
    })
  );
}

filterExams.PATH = '/exams/filter';
