/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ExamDetailDto } from '../../models/exam-detail-dto';

export interface GetExamDetail$Params {
  'exam-id': string;
  department?: string;
  block?: string;
}

export function getExamDetail(http: HttpClient, rootUrl: string, params: GetExamDetail$Params, context?: HttpContext): Observable<StrictHttpResponse<ExamDetailDto>> {
  const rb = new RequestBuilder(rootUrl, getExamDetail.PATH, 'get');
  if (params) {
    rb.path('exam-id', params['exam-id'], {});
    rb.query('department', params.department, {});
    rb.query('block', params.block, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ExamDetailDto>;
    })
  );
}

getExamDetail.PATH = '/exams/detail/{exam-id}';
