/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ExamNameDto } from '../../models/exam-name-dto';

export interface GetExamNamesByExamType$Params {
  'exam-type': 'TEST' | 'ERMP' | 'USMLE_STEP_1' | 'USMLE_STEP_2';
}

export function getExamNamesByExamType(http: HttpClient, rootUrl: string, params: GetExamNamesByExamType$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<ExamNameDto>>> {
  const rb = new RequestBuilder(rootUrl, getExamNamesByExamType.PATH, 'get');
  if (params) {
    rb.path('exam-type', params['exam-type'], {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<ExamNameDto>>;
    })
  );
}

getExamNamesByExamType.PATH = '/exams/list/{exam-type}';
