/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ExamDto } from '../../models/exam-dto';

export interface GetExamById$Params {
  'exam-id': string;
}

export function getExamById(http: HttpClient, rootUrl: string, params: GetExamById$Params, context?: HttpContext): Observable<StrictHttpResponse<ExamDto>> {
  const rb = new RequestBuilder(rootUrl, getExamById.PATH, 'get');
  if (params) {
    rb.path('exam-id', params['exam-id'], {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ExamDto>;
    })
  );
}

getExamById.PATH = '/exams/{exam-id}';
