/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PageResponseResourceDto } from '../../models/page-response-resource-dto';

export interface FilterResources$Params {
  title?: string;
  type?: string;
  requiredSubLevel?: string;
  'parent-id'?: string;
  'has-child-resources'?: boolean;
  page?: number;
  size?: number;
}

export function filterResources(http: HttpClient, rootUrl: string, params?: FilterResources$Params, context?: HttpContext): Observable<StrictHttpResponse<PageResponseResourceDto>> {
  const rb = new RequestBuilder(rootUrl, filterResources.PATH, 'get');
  if (params) {
    rb.query('title', params.title, {});
    rb.query('type', params.type, {});
    rb.query('requiredSubLevel', params.requiredSubLevel, {});
    rb.query('parent-id', params['parent-id'], {});
    rb.query('has-child-resources', params['has-child-resources'], {});
    rb.query('page', params.page, {});
    rb.query('size', params.size, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PageResponseResourceDto>;
    })
  );
}

filterResources.PATH = '/resources/filter';
