/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ResourceInfoDto } from '../../models/resource-info-dto';

export interface GetListOfCollections$Params {
  'lecture-id': string;
}

export function getListOfCollections(http: HttpClient, rootUrl: string, params: GetListOfCollections$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<ResourceInfoDto>>> {
  const rb = new RequestBuilder(rootUrl, getListOfCollections.PATH, 'get');
  if (params) {
    rb.path('lecture-id', params['lecture-id'], {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<ResourceInfoDto>>;
    })
  );
}

getListOfCollections.PATH = '/resources/collection-list/{lecture-id}';
