/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ChoiceDto {
  id?: string;
  isCorrect?: boolean;
  percentage?: number;
  text?: string;
}
