/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateExamDto {
  description?: string;
  duration: number;
  examType: 'TEST' | 'ERMP' | 'USMLE_STEP_1' | 'USMLE_STEP_2';
  id?: string;
  randomQuestionCount?: number;
  requiredSubLevel: 'NONE' | 'BASIC' | 'ADVANCED' | 'PREMIUM';
  title?: string;
  year: number;
}
