/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateResourceDto {
  contentPath?: string;
  department?: string;
  description?: string;
  id?: string;
  parentResourceId?: string;
  previewResourceId?: string;
  requiredSubLevel: 'FREE' | 'BASIC' | 'ADVANCED' | 'PREMIUM';
  title?: string;
  type: 'EXAM' | 'NOTE' | 'VIDEO' | 'BOOK' | 'COLLECTION';
}
