/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateExamDto {
  department?: string;
  description?: string;
  duration: number;
  id?: string;
  requiredSubLevel: 'NONE' | 'BASIC' | 'ADVANCED' | 'PREMIUM';
  title?: string;
}
