/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateExamDto {
  department?: string;
  description?: string;
  duration?: string;
  id?: string;
  requiredSubLevel: 'FREE' | 'BASIC' | 'ADVANCED' | 'PREMIUM';
  title?: string;
}
