/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { QuestionDto } from '../models/question-dto';
export interface ExamDetailDto {
  description?: string;
  duration?: number;
  previewQuestions?: Array<QuestionDto>;
  questions?: Array<QuestionDto>;
  title?: string;
}
