/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { QuestionDetailDto } from '../models/question-detail-dto';
export interface ExamDetailDto {
  description?: string;
  duration?: number;
  questions?: Array<QuestionDetailDto>;
  requiredSubLevel?: 'NONE' | 'BASIC' | 'ADVANCED' | 'PREMIUM';
  title?: string;
}
