/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ExamDto {
  description?: string;
  duration?: number;
  examType?: 'TEST' | 'ERMP' | 'USMLE_STEP_1' | 'USMLE_STEP_2' | 'NGAT' | 'LICENSURE';
  id?: string;
  numberOfQuestions?: number;
  randomQuestionCount?: number;
  requiredSubLevel?: 'NONE' | 'BASIC' | 'ADVANCED' | 'PREMIUM';
  title?: string;
  year?: number;
}
