/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ExamDto {
  department?: string;
  description?: string;
  duration?: number;
  id?: string;
  numberOfQuestions?: number;
  requiredSubLevel?: 'NONE' | 'BASIC' | 'ADVANCED' | 'PREMIUM';
  title?: string;
}
