/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Choice } from '../models/choice';
export interface QuestionDto {
  choices?: Array<Choice>;
  explanation?: string;
  imgUrls?: Array<string>;
  questionText?: string;
}
