/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ResourceDetailDto {
  contentPath?: string;
  department?: string;
  description?: string;
  id?: string;
  parentResource?: string;
  parentResourceId?: string;
  requiredSubLevel?: 'NONE' | 'BASIC' | 'ADVANCED' | 'PREMIUM';
  title?: string;
  type?: 'EXAM' | 'NOTE' | 'VIDEO' | 'BOOK' | 'COLLECTION';
}
