/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ResourceDto {
  contentPath?: string;
  description?: string;
  id?: string;
  parentResourceId?: string;
  parentResourceTitle?: string;
  previewContentPath?: string;
  requiredSubLevel?: 'NONE' | 'BASIC' | 'ADVANCED' | 'PREMIUM';
  title?: string;
  type?: 'EXAM' | 'READING_MATERIAL' | 'VIDEO' | 'BOOK' | 'READING_MATERIALS' | 'LECTURE_VIDEOS' | 'LECTURE_NOTES' | 'ERMP' | 'USMLE_STEP_1' | 'USMLE_STEP_2' | 'NGAT' | 'LICENSURE' | 'LECTURES' | 'BOOKS';
}
