/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ResourceDto } from '../models/resource-dto';
export interface ResourceCollectionDto {
  department?: string;
  description?: string;
  requiredSubLevel?: 'FREE' | 'BASIC' | 'ADVANCED' | 'PREMIUM';
  resources?: Array<ResourceDto>;
  title?: string;
  type?: 'EXAM' | 'NOTE' | 'VIDEO' | 'BOOK' | 'COLLECTION';
}
