/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ResourceDto {
  contentPath?: string;
  department?: string;
  description?: string;
  id?: string;
  parentResourceId?: string;
  parentResourceTitle?: string;
  previewContentPath?: string;
  requiredSubLevel?: 'NONE' | 'BASIC' | 'ADVANCED' | 'PREMIUM';
  title?: string;
  type?: 'EXAM' | 'READING_MATERIAL' | 'VIDEO' | 'BOOK' | 'LECTURE_VIDEOS' | 'LECTURE_NOTES';
}
