/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface SubPlanDto {
  benefits?: Array<string>;
  durationInMonth?: number;
  enabled?: boolean;
  id?: string;
  level?: 'NONE' | 'BASIC' | 'ADVANCED' | 'PREMIUM';
  price?: number;
}
