/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface SubscriptionDto {
  endDate?: string;
  externalId?: string;
  level?: 'NONE' | 'BASIC' | 'ADVANCED' | 'PREMIUM';
  startDate?: string;
}
