/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UpdateSubPlanDto {
  benefits: Array<string>;
  durationInMonth: number;
  enabled: boolean;
  id?: string;
  level?: string;
  price: number;
}
