/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CorrectAnswer } from '../models/correct-answer';
import { UserAnswer } from '../models/user-answer';
export interface UpdateUserExamDto {
  correctAnswers?: Array<CorrectAnswer>;
  examId?: string;
  mode?: 'STUDY' | 'TEST';
  status?: 'IN_PROGRESS' | 'COMPLETED';
  timeLeftInMinutes?: number;
  userAnswers?: Array<UserAnswer>;
}
