/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CorrectAnswer } from '../models/correct-answer';
import { UserAnswer } from '../models/user-answer';
export interface UserExamDto {
  examId?: string;
  lastModifiedDate?: string;
  mode?: string;
  status?: 'IN_PROGRESS' | 'COMPLETED';
  studyModeCorrectAnswers?: Array<CorrectAnswer>;
  studyModeUserAnswers?: Array<UserAnswer>;
  testModeCorrectAnswers?: Array<CorrectAnswer>;
  testModeUserAnswers?: Array<UserAnswer>;
  timeLeftInMinutes?: number;
  userId?: string;
}
