/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UserAggregateData {
  advanced_subscribers?: number;
  basic_subscribers?: number;
  premium_subscribers?: number;
  registered_users?: number;
}
