/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UserDto {
  email?: string;
  enabled?: boolean;
  endDate?: string;
  id?: string;
  registeredDate?: string;
  startDate?: string;
  subscriptionLevel?: 'NONE' | 'BASIC' | 'ADVANCED' | 'PREMIUM';
  username?: string;
}
