spring:
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 1GB
      max-request-size: 1GB

springdoc:
  default-produces-media-type: application/json

server:
  servlet:
    context-path: /api

