/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SubscriptionResponse } from '../../models/subscription-response';

export interface GetCurrentSubscription$Params {
  'user-id': string;
}

export function getCurrentSubscription(http: HttpClient, rootUrl: string, params: GetCurrentSubscription$Params, context?: HttpContext): Observable<StrictHttpResponse<SubscriptionResponse>> {
  const rb = new RequestBuilder(rootUrl, getCurrentSubscription.PATH, 'get');
  if (params) {
    rb.path('user-id', params['user-id'], {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<SubscriptionResponse>;
    })
  );
}

getCurrentSubscription.PATH = '/subscription/current/{user-id}';
