/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { getFile } from '../fn/files/get-file';
import { GetFile$Params } from '../fn/files/get-file';
import { streamVideo } from '../fn/files/stream-video';
import { StreamVideo$Params } from '../fn/files/stream-video';

@Injectable({ providedIn: 'root' })
export class FilesService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `streamVideo()` */
  static readonly StreamVideoPath = '/files/stream-video';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `streamVideo()` instead.
   *
   * This method doesn't expect any request body.
   */
  streamVideo$Response(params: StreamVideo$Params, context?: HttpContext): Observable<StrictHttpResponse<Blob>> {
    return streamVideo(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `streamVideo$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  streamVideo(params: StreamVideo$Params, context?: HttpContext): Observable<Blob> {
    return this.streamVideo$Response(params, context).pipe(
      map((r: StrictHttpResponse<Blob>): Blob => r.body)
    );
  }

  /** Path part for operation `getFile()` */
  static readonly GetFilePath = '/files/get-file';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getFile()` instead.
   *
   * This method doesn't expect any request body.
   */
  getFile$Response(params: GetFile$Params, context?: HttpContext): Observable<StrictHttpResponse<Blob>> {
    return getFile(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getFile$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getFile(params: GetFile$Params, context?: HttpContext): Observable<Blob> {
    return this.getFile$Response(params, context).pipe(
      map((r: StrictHttpResponse<Blob>): Blob => r.body)
    );
  }

}
