name: NEUS Frontend Pipeline

on:
  push:
    branches:
      - pipeline
    paths:
      - neus-ui/**
      - docker/frontend/**
      - 'docker-compose.yml'
      - .github/workflows/*-frontend.yml

jobs:
  build-image:
    name: build frontend docker image
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: login to dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}

      - name: build and push to dockerhub
        uses: docker/build-push-action@v5
        with:
          context: neus-ui
          file: docker/frontend/Dockerfile
          push: true
          platform: linux/amd64
          tags: ${{secrets.DOCKERHUB_USERNAME}}/neus-ui:latest

#  deploy:
#    name: deploy-frontend
#    runs-on: ubuntu-latest
#    needs: [ build-image ]
#    steps:
#      - name: Deploy to digitalOcean droplet
#        uses: appleboy/ssh-action@master
#        with:
#          host: ${{ secrets.DROPLET_IP }}
#          username: ${{ secrets.DROPLET_USERNAME }}
#          key: ${{ secrets.SSH_PRIVATE_KEY }}
#          script: |
#            cd ~
#            docker pull habtamudires/neus-ui:latest
#            docker-compose up -d frontend
#            docker image prune -a -f