name: neus backend pipeline (native)

on:
  push:
    branches:
      - pipeline
    paths:
      - neus-api/**
      - docker/backend/**
      - 'docker-compose.yml'
      - .github/workflows/*-backend.yml

jobs:
  build-image:
    runs-on: ubuntu-latest
    name: build docker image (native)
    steps:
      - name: checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: setup docker buildx
        uses: docker/setup-buildx-action@v3

      - name: login to dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: build and push docker image
        uses: docker/build-push-action@v5
        with:
          context: neus-api
          file: docker/backend/Dockerfile
          push: true
          platform: linux/amd64
          tags: |
            ${{secrets.DOCKERHUB_USERNAME}}/neus-api:latest

  deploy:
    name: deploy-backend
    runs-on: ubuntu-latest
    needs: [ build-image ]
    steps:
      - name: Deploy to digitalOcean droplet
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: ${{ secrets.DROPLET_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/neus-api:latest
            docker-compose up -d backend
            docker image prune -a -f